channels:
  - defaults
  - conda-forge
dependencies:
  - cairo
  - ffmpeg
  - matplotlib
  - matplotlib-base
  - matplotx
  - numexpr
  - numpy
  - numpy-base
  - pdf2image
  - pillow
  - pip
  - poppler
  - poppler-data
  - pthread-stubs
  - pypdf
  - pytest
  - python
  - python-dateutil
  - python-tzdata
  - python_abi
  - pytz
  - scikit-learn
  - pip:
      - opencv-contrib-python
      - opencv-python
      - pyparsing
      - PyMuPDF
      - pyside6
      - shapely
